name: Create and publish a LLM Web UI image
on:
  workflow_dispatch:
jobs:
  build-and-push-image:
    name: Build and push ${{ github.ref_name }}
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-22.04
    env:
      REGISTRY: ghcr.io
    steps:
      - name: Log in to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Sparse-checkout repository for actions
        if: ${{ ! startsWith(github.ref_name, 'base/') }}
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github/actions
      - name: Free up disk space
        if: ${{ ! startsWith(github.ref_name, 'base/') }}
        uses: ./.github/actions/disk-cleanup
      - name: Extract image `<name>` and `<tag>` from the ref
        id: image
        env:
          REF_NAME: ${{ github.ref_name }}
        run: |
          echo "::set-output name=name::${REF_NAME%/*}"
          echo "::set-output name=tag::${REF_NAME##*/}"
      - name: Build and push the image
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:${{ steps.image.outputs.name }}"
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository }}/${{ steps.image.outputs.name }}:${{ steps.image.outputs.tag }}
